version: "3"

services:
  backend:
    image: schlemihl/wishlist-backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend
    expose:
      - 8080
    volumes:
      - log_backend:/app/log

  frontend:
    image: nginx
    depends_on:
      - backend
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    networks:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - frontend_nginx_conf:/etc/nginx
      - log_nginx:/var/log/nginx
      - letsencrypt_volume:/etc/letsencrypt
      - www_volume:/var/frontend/www

networks:
  backend:

volumes:
  frontend_public:
  frontend_nginx_conf:
  log_nginx:
  log_backend:
  letsencrypt_volume:
  www_volume:
